// <auto-generated />
using System;
using BeerWulf.Data.Impl.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeerWulf.Data.Impl.EF.Migrations
{
    [DbContext(typeof(BeerWulfProductReviewDbContext))]
    [Migration("20221125173806_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Product")
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BeerWulf.Domain.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.ToTable("Products", "Product");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "A crisp and refreshing session IPA with fruity notes and hints of grass and tea. Fresh and frisky with a clean bitter finish exactly how a session IPA should be.",
                            Name = "Fourpure Session IPA - 2L SUB Keg",
                            Price = 11.99m
                        },
                        new
                        {
                            Id = 2L,
                            Description = "This beer was first brewed in Singapore in 1932, so is made for hotter temperatures and is bound to help satisfy your thirst. The recipe includes rice, malted barley and American Zeus hops, so has a variety of flavours to please the palette. Lagers are often the go-to when pouring pints for a group of friends, so next time you have people over, some Tiger will bring smiles all around.",
                            Name = "Tiger - 2L SUB Keg",
                            Price = 9.34m
                        },
                        new
                        {
                            Id = 3L,
                            Description = "This beer was first brewed in Singapore in 1932, so is made for hotter temperatures and is bound to help satisfy your thirst. The recipe includes rice, malted barley and American Zeus hops, so has a variety of flavours to please the palette. Lagers are often the go-to when pouring pints for a group of friends, so next time you have people over, some Tiger will bring smiles all around.",
                            Name = "This beer was first brewed in Singapore in 1932, so is made for hotter temperatures and is bound to help satisfy your thirst. The recipe includes rice, malted barley and American Zeus hops, so has a variety of flavours to please the palette. Lagers are often the go-to when pouring pints for a group of friends, so next time you have people over, some Tiger will bring smiles all around.",
                            Price = 26.24m
                        },
                        new
                        {
                            Id = 4L,
                            Description = "Villacher Marzen is a very drinkable lager where the malty and toasted bread-like taste and smell is the highlight of the beer. The presence of hops is not noticeable in the smell and taste, but the beer does have a moderate hop bitterness. This beer has a radiant, golden yellow colour and fine-bubble foam whilst being incredibly refreshing and sparkling to taste. It was awarded the golden DLG seal in 2014 and 2015",
                            Name = "Villacher Märzen - 8L BLADE Keg",
                            Price = 28.49m
                        });
                });

            modelBuilder.Entity("BeerWulf.Domain.Models.ProductReview", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("ProductRecommended")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<byte>("Score")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("ProductId");

                    b.ToTable("ProductReviews", "Product");
                });

            modelBuilder.Entity("BeerWulf.Domain.Models.ProductReview", b =>
                {
                    b.HasOne("BeerWulf.Domain.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BeerWulf.Domain.Models.Product", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
